spring:
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/mydatabase?authSource=admin
      security:
        authorization: enabled
    redis:
      host: localhost
      port: 6379
      username: cache_db
      password: password123

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password123

  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false

  mail:
    host: localhost
    port: 1025
    username: dobby
    password: dobby
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: bXlwZXJmZWN0c2VjcmV0a2V5dG8gdXNlIHdpdGggSlBXVA==
      expiration: 60000000
