server:
  port: 8080
  servlet:
    context-path: /api/v1/
spring:
  application:
      name: e2eeChatApp
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  default-produces-media-type: application/json

