server:
  port: 8080
spring:
  application:
      name: e2eeChatApp
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/mydatabase?authSource=admin
      security:
        authorization: enabled

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password123

  logging:
    level:
      org.springframework: DEBUG
      com.mongodb: DEBUG

  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false